use_frameworks!

platform :ios, '8.0'

target 'YGElfControl_Example' do
    
  pod 'YGElfControl', :path => '../'
#    pod 'YGElfControl', '~>0.1.2'





  target 'YGElfControl_Tests' do
    inherit! :search_paths
    
  end
end
